### ISSUE TITLE
No Battery Icon for laptops

### ISSUE THREAD

**Issue by Birdabo404** [p3nguin-kun/penguinRice#1]
Hello, I have recently installed your rice using your install.sh and everything is working correctly apart from the battery icon on the polybar, I have checked the configuration file and I see the battery line being there but it's still not appearing on the bar. I would like to ask why this is, thank you and merry Christmas

![386871041_872689181203325_2584941888784006498_n](https://github.com/p3nguin-kun/penguinRice/assets/140108872/bb3cafbe-7ece-4f64-814b-4c78fe249734)
!!

**Comment by p3nguin-kun** [comment]
read [this](https://github.com/polybar/polybar/wiki/Module:-battery)

**Comment by Birdabo404** [comment]
> read [this](https://github.com/polybar/polybar/wiki/Module:-battery)

Thanks I figured it out, I was just missing one line which is full-at: X 

Issue Solved - Closing
